# Generated by Django 4.2.2 on 2023-07-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='C:\\Entregables\\EntregablePython\\Python\\home\\static\\Home\\img'),
        ),
    ]
