# Generated by Django 4.2.2 on 2023-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
