# Generated by Django 4.2.2 on 2023-07-20 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
