# Generated by Django 4.2.2 on 2023-11-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='umbral_minimo',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
