# Generated by Django 4.2.2 on 2023-11-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_venta_precio_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
    ]
